apiVersion: v1 # String
kind: Pod # String
metadata: # Dictionary
  name: myapp-pod
  labels: # Dictionary
    app: myapp  # Key value pairs
spec:
  containers: # List
    - name: myapp
      image: sdhamija1/nginx_image1:v1-release
      ports: 
        - containerPort: 80


    
